apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBNvjZP5mpQPyMfZvPKakVVqHH6mXd1SlfrEEIrNGvPQR9PHmGTJchqFugL2yHbPxHjXtldY9mP0hYZkmvVdg1PFG2TB/wEN7S7r9H82T+6ClmR0YKJ7kjRpVIyne/UnyKK68KkxNdKwo0nvb9P56VvzfXEz+g3HbpcG+t4c+XgFcNWF6Ch+VuSl9ifGWhdbb49y2rfRw6GgP5WhcmgSuwYdgc7xl1z9LyDrjr/A9TncgBeSNzETlxEfmfwkqBjdnm7lFI6F5bW8MM7vrOSmsbRWzYN4iCvdsucsr7z7oW9dVKdm2f5bc2CCEoF0j5WFoqGVsjWUMRfbdFMLqEn9UTG6MC/6YXKIJeLcgN1qD2YoWyQwjPd7kH6W6dhemE8F+OBTwxdPsIzZn9Npm3oeLV9h3CdaBIrYq+TTY5hsC9j552Rah2f6eIf3ilN5OISKz7h/nUDLNemVTSTdH4gQ18VpcTGnVWFzY9fVqLjMgWWvaqfeGt00OhsfYRedtRTxzp+RMoH9aRwbwFGRz+jIKVYYTAEdCrrGIbOUAd9aWDpZL4SpJYbNhrK0SACrX39CbrH4k2FnxjPWOcxOAzLjGVn74WJjEizAh1bRI3cge9I/xkdtt2lwkTnQkql+1ha20oTQbGKiFhmf2OcixNLpI/A5GQaGKgGD/6+nG+9CmBu1BMc8LBpjrgg4wWik4MEh226nL8JJFIQq6fO0IzgKLnydFn7zDrjTv6n2kHl6KFAmCRqZYjnke/d
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
