apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBjWQSRZgAcn6xIr9SFJmuTOQkTMUtcc8VCDcE/UU3NWMakgpygqqf5zWkc6hw5rcFH+q4X0E2dSBqjJiUtGFMFOW1KY9nuzRshj2ZCWVpcQQvpX4KCV0ntpyjz/zu3+/y0sOWSVQL+AQsLFt43qKoTTZ/p5dQFXnmh5ww2jPj6DVBibfPG+nA7Bwp98yQEG/sgjqnP97r/FtcVugD9/qQZJTXXrKHq8HOsCSXWhFblHVsxtxcYyr/LZA5stNHjSQvTeT0i7c6/5ljK4lkMNCWMq5iH/sXHpI3ETOHJv4CLC6OZPLeA6qWIV9faLkCrZEpT5cotr7kGRG+WEsA/VIP0fjJEU1xG0qZcEfmWqiBj/BtyKb9797i8Kfy05YbWxk3QyFYB30/opWOeHWJXo/vzlNiQ4lBGlPeKIbF0eIulX7oedaXVcvvp2FwlSc/QM77WXZbYSSmJYereupwzYJztPzl6CwbC5mIqx2hpfz24wsaf9puYALrzF3cjMzniJNbQFBh4YD2YUhrNnMHokUgJNZ4KWAFFkLyqE+Q5TkoJ/UmLADie6c9xiJ0JujqqNRjs45geeBtTukBriE0kEgHHFBJiO3OYxuAW0lVMD2TKB1Wy3kwkyEuyO5m7IhTn7Fgx690X9xWQyvqhWAARqvxZjH6TVIKshQHh9H6UWjK2bRC9gli8hdXBPv0eQJ5IBqS23R0vVUE0Mi0xZlubu5ouIUE92pswItORAUOyX1VmSZpPfJOsErjO
  template:
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque
